### ISSUE TITLE
conky not showing on desktop preview

### ISSUE THREAD

**Issue by jgabriel98** [Rayzr522/now-clocking#4]
I don't know if this is a conky normal issue (a unsolvable one), or just a conky config issue.

But the **now-clocking** conky does not apear on the desktop preview:
![Captura de tela de 2020-10-04 12-33-53](https://user-images.githubusercontent.com/37881981/95019927-973c9100-063e-11eb-8e38-c3dbca2e5d23.png)

![nowClocking_bug2](https://user-images.githubusercontent.com/37881981/95020117-96f0c580-063f-11eb-8288-ff6720299620.gif)

**Comment by foxfirecodes** [comment]
the gnome/pop desktop preview feature does not show desktop widgets
